version: "3"

services:
  care:
    build:
      dockerfile: app.dockerfile
      context: .
    image: care/php
    container_name: care
    restart: always
    ports:
      -  "8081:80"
    volumes:
      - ${APPLICATION}:/app
    depends_on:
      - "mysql"
    networks: 
      - care-network

  mysql:
    image: mysql:5.7
    container_name: mysql

    networks:
        - care-network    
    ports:
      - "3306:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: care
    restart: always


networks: 
  care-network:
      driver: bridge
