version: "3"

services:
  webjumpapp:
    build:
      dockerfile: app.dockerfile
      context: .
    image: webjumpapp/php
    container_name: webjumpapp
    restart: always
    ports:
      -  "8081:80"
    volumes:
      - ${APPLICATION}:/app
    depends_on:
      - "mysql"
    networks: 
      - webjump-network

  mysql:
    image: mysql:5.7
    container_name: mysql

    networks:
        - webjump-network    
    ports:
      - "3306:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webjump-products
      
    restart: always


networks: 
  webjump-network:
      driver: bridge
