<div class="container">
    
    <?php $this->renderView('alerts/_success') ?>
    <?php $this->renderView('alerts/_errors') ?>

    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>
        
        <form action="/upload/store" method="post" enctype="multipart/form-data" accept-charset="utf-8">
            <div class="col-sm-10">
                <div class="form-group <?php echo ($this->errors['file']) ? 'has-error' : '' ?>">
                    <label for="file" class="control-label">Arquivo</label>
                    <input required="true" type="file" name="file"
                           value="<?php echo (isset($this->inputs['file'])) ? $this->inputs['file'] : '' ?>">
                    <?php if ($this->errors['file']): ?>
                        <span class="help-block"><?php echo $this->errors['file'] ?></span>
                    <?php endif; ?>
                </div>
            </div>

            <div class="col-xs-12">
                <a href="/uploads" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
</div>