<div class="container">
    <h1 class="h1">
        <?php echo $this->getPageTitle(); ?>
        <?php if($this->auth->check()) : ?>
        <a href="/upload/create" class="btn btn-primary pull-right">
            <i class="glyphicon glyphicon-plus-sign"></i> Importar Notas
        </a>
        <?php endif; ?>
    </h1>

    <?php $this->renderView('alerts/_success') ?>
    <?php $this->renderView('alerts/_errors') ?>

    <div class="card-content">
        <div class="table-responsive">
            <table class="table data-table">
                <?php echo $this->view->files; ?>
            </table>
        </div>
    </div>
</div>